import type { Metadata } from "next";
import { be_vietnam_pro } from "./fonts";
import "./css/globals.css";

import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32" />
      </head>
      <body className={`${be_vietnam_pro.className} text-base font-normal leading-normal`}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
};
